### ISSUE TITLE
Roadmap to 1.0

### ISSUE THREAD

**Issue by gxespino** [gxespino/paradigm#1]
I'm not 100% sold on any of these features as of yet. Mainly I just want a place to store and discuss ideas as they pop up. Once the roadmap is finalized, I'll be sure to make that clear.

- [x]  ~~Base Install generator~~
- [x]  ~~Nested generators~~
- [ ]  Add removal of generated files
- [ ]  Configuration options
- [ ]  config: RSpec templates
- [ ]  config: Different Service paradigms
- [ ]  config: Disable appending Service to filename 
- [ ]  Better documentation overall
- [ ]  Documentation of generators with links to paradigm explanations + demo apps
- [ ]  Demo applications of each service paradigm

If you can think of other features that should be implemented, please post an issue and start a discussion!
